name = "FluidProperties"
uuid = "d16f1b92-71d3-42f3-aafa-43e5bb0efda8"
authors = ["Your Name <you@example.com>"]
version = "0.1.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulMoles = "999f2bd7-36bf-5ba7-9bc1-c9473aa75374"

[compat]
Unitful = "1.24.0"
UnitfulMoles = "0.1.1"
