name = "FluidProperties"
uuid = "d16f1b92-71d3-42f3-aafa-43e5bb0efda8"
authors = ["m.kearney@unimelb.edu.au", "rafaelschouten@gmail.com"]
version = "0.1.0"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulMoles = "999f2bd7-36bf-5ba7-9bc1-c9473aa75374"

[compat]
Aqua = "0.8"
PhysicalConstants = "0.2.4"
Test = "1"
Unitful = "1.24.0"
UnitfulMoles = "0.1.1"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
