library(NicheMapR)
rh <- 40
elevation <- 1000 # m
bp <- get_pressure(elevation)
T_airs <- seq(-20, 80, 1)
WETAIR.out <- WETAIR(db = T_airs, rh = rh, bp = bp)
DRYAIR.out <- DRYAIR(T_airs, bp = bp)
WATERPROP.out <- lapply(T_airs, WATERPROP)
CP_water     <- sapply(WATERPROP.out, function(x) x$CP)
DENSTY_water <- sapply(WATERPROP.out, function(x) x$DENSTY)
THCOND_water <- sapply(WATERPROP.out, function(x) x$THCOND)
VISDYN_water <- sapply(WATERPROP.out, function(x) x$VISDYN)

write.csv(c(rh, elevation), '../data/pars.csv')
write.csv(T_airs, '../data/T_airs.csv')
write.csv(DRYAIR.out$densty, '../data/denair_dry.csv')
write.csv(DRYAIR.out$visdyn, '../data/visdyn.csv')
write.csv(DRYAIR.out$viskin, '../data/viskin.csv')
write.csv(DRYAIR.out$difvpr, '../data/difvpr.csv')
write.csv(DRYAIR.out$thcond, '../data/thcond.csv')
write.csv(DRYAIR.out$ggroup, '../data/ggroup.csv')
write.csv(DRYAIR.out$bbemit, '../data/bbemit.csv')
write.csv(DRYAIR.out$emtmax, '../data/emtmax.csv')

write.csv(WETAIR.out$esat, '../data/esat.csv')
write.csv(WETAIR.out$e, '../data/e.csv')
write.csv(WETAIR.out$vd, '../data/vd.csv')
write.csv(WETAIR.out$rw, '../data/rw.csv')
write.csv(WETAIR.out$tvinc, '../data/tvinc.csv')
write.csv(WETAIR.out$denair, '../data/denair_wet.csv')
write.csv(WETAIR.out$cp, '../data/cp.csv')
write.csv(WETAIR.out$wtrpot, '../data/wtrpot.csv')

write.csv(CP_water, '../data/CP_water.csv')
write.csv(DENSTY_water, '../data/DENSTY_water.csv')
write.csv(THCOND_water, '../data/THCOND_water.csv')
write.csv(VISDYN_water, '../data/VISDYN_water.csv')
